[project]
name = "kill-process-mcp"
version = "1.1"
description = "AI-powered cross-platform MCP server exposing LLM-accessible tools to list and terminate OS processes via natural language queries"
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]
authors = [{ name = "Michal Szymanski", email = "misiektoja-github@rm-rf.ninja" }]
requires-python = ">=3.13"
dependencies = [
  "mcp>=1.9.4",
  "psutil"
]

[project.urls]
Homepage = "https://github.com/misiektoja/kill-process-mcp"
Source   = "https://github.com/misiektoja/kill-process-mcp"
Changelog= "https://github.com/misiektoja/kill-process-mcp/blob/main/RELEASE_NOTES.md"

[project.scripts]
kill-process-mcp = "kill_process_mcp:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
